### ISSUE TITLE
Critical: runner latest image tag is removed from quay.io

### ISSUE THREAD

**Issue by siavashs** [evryfs/github-actions-runner-operator#396] opened 2022-03-04 09:20 UTC
The `latest` image tag of `evryfs/github-actions-runner` has disappeared from quay.io.
https://quay.io/repository/evryfs/github-actions-runner?tab=tags

Today we noticed our runners were failing to start with `ImagePullBackOff`.

I understand this is an opensource project and using it comes with risks but the released artifacts are like a service you provide which needs to be maintained.

**Comment by davidkarlsen** [comment] 2022-03-04 18:11
Sorry about that - but latest has not been updated for a while. Use master tag

**Comment by siavashs** [comment] 2022-03-05 10:32
No problem, I think you could have made `latest` tag to point to `master` tag instead of deleting it.
Even [the sample configuration](https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L65) is still pointing to the `latest` tag which needs to be updated.

**Comment by davidkarlsen** [comment] 2022-03-05 10:50
It was an oversight. There is another issue about it which I'll fix as soon as I am back from holiday.

**Comment by davidkarlsen** [comment] 2022-03-06 21:45
Fixed in https://github.com/evryfs/github-actions-runner-operator/commit/a10c102cae80a0679623bfb9998a43d246d985d2, duplicate of https://github.com/evryfs/github-actions-runner/issues/124

**Closed by davidkarlsen** 2022-03-06 21:45 UTC
